// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the 
// first 10 terms will be:   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

let a = 1;
let b = 2;
let sum = 0 ;
let total = 0;

function fibSum(limit){
    while (b < limit){

         // Check the number is even or not
        if (b % 2 == 0){
            total += b;
        }
        sum = a + b;
        a = b;
        b = sum;
    }
    console.log(total);
}

fibSum(4e6);     //  4e6 = 4000000  = 4 & 6 zeroes